INTGR-160
Geotab/sdk pull request #342
Opened 2023-11-01 20:10 UTC by kmets89

2023-11-04 00:59 UTC, jyalenkatian requested changes

2023-11-04 00:59 UTC, jyalenkatian commented on src/components/CodeSamplesContainer/CodeSampleStyle.tsx
> +        textAlign: "left"
We're missing some of the formatting listed in Figma
```suggestion
        fontSize: "12px",
        fontWeight: "400",
        lineHeight: "16px",
        textAlign: "left",
        borderRadius: "8px",
        fontFamily: "Roboto",
        overflowY: "auto",
        padding: "24px"
```

2023-11-04 00:59 UTC, jyalenkatian commented on src/variables.scss
> +$lightGray:#F9FAFB;
The gray background color for the header is slightly different than the one for the top of the page. Header is #F9FAFB while the top of the page that includes the breadcrumb and title should be #F8F9FC.

2023-11-04 00:59 UTC, jyalenkatian commented on src/pages/pages.scss
>  }
```suggestion
  margin-block-end: 0px;
}
```

2023-11-04 00:59 UTC, jyalenkatian commented on src/pages/pages.scss
>  }
Would be better to call the .grayBackground class something else (i.e. pageHeading) and it should also have a padding of "16px 24px" while the title margin-block-end should be 0px.

2023-11-06 18:50 UTC, williamwgeotab reviewed
Minor suggestions

2023-11-06 20:07 UTC, williamwgeotab commented on src/components/CodeSamplesContainer/CodeSampleStyle.tsx
> +    };
Code sample styling will be revisited in the future

2023-11-06 20:12 UTC, williamwgeotab commented
Latest commit looks good! 
- All functionality appear to be working fine
- CSS issues (naming, color code consistency, etc) will be addressed in the near future
- Newly merged "Using Custom Telematics Devices" doesn't have breadcrumbs but can be addressed in the future

Merging PR

2023-11-06 20:15 UTC, merged