INTGR-166: "Add-Ins for Data Storage" page
Geotab/sdk pull request #349
Opened 2023-11-08 01:51 UTC by tranjennie

2023-11-17 23:12 UTC, kmets89 requested changes

2023-11-17 23:12 UTC, kmets89 commented on src/pages/myGeotab/addIns/addInStorage.tsx
> +            <Accordion summary="What is the Storage API?" p={StorageAPI}></Accordion>
please capitalize all words in all accordion titles

2023-11-17 23:12 UTC, kmets89 commented on src/pages/myGeotab/addIns/addInStorage.tsx
> +    <h2>Additional Resources</h2>
according to current page markup this should be its own section/accordion

2023-11-17 23:12 UTC, kmets89 commented on src/pages/myGeotab/addIns/addInStorage.tsx
> +        <h3>Legacy Property 'Data'</h3>
all ### from markup should be h2, not h3

2023-11-17 23:12 UTC, kmets89 commented on src/pages/myGeotab/addIns/addInStorage.tsx
> +const CreatingAddInDataObject: ReactNode = <div className="paragraph">
use camel case for these variables

2023-11-20 20:38 UTC, tranjennie commented
Hello @kmets89 !
made some changes: 
modify heading levels from h3 to h2, change titled, added TODO comments

2023-11-21 17:39 UTC, merged