INTGR: feat/Implement Footer component
Geotab/sdk pull request #356
Opened 2023-11-16 00:49 UTC by williamwgeotab

- Add initial footer component content
- Add styling matching figma
- Add logo and divider svg
- Add footer component to App.tsx

2023-11-17 22:09 UTC, kmets89 requested changes

2023-11-17 22:09 UTC, kmets89 commented on src/components/Footer/Footer.tsx
> +            <div className="footer-logo-container">
looks like this class doesn't exist?

2023-11-17 22:09 UTC, kmets89 commented on src/components/Footer/footer.scss
> +    font-family: Roboto;
the font family is set in project level css file, please don't introduce redundant styling

2023-11-20 21:56 UTC, williamwgeotab commented on src/components/Footer/Footer.tsx
> +          <div className="footer-container__left">
fixed, ty!

2023-11-20 23:26 UTC, williamwgeotab commented
@kmets89 merged most recent changes of INTGR-123 & resolved the outstanding items. Thanks!

2023-11-21 02:54 UTC, kmets89 approved these changes

2023-11-21 02:54 UTC, merged