INTGR-157 Concepts Page
Geotab/sdk pull request #368
Opened 2023-11-30 17:10 UTC by wajihqazi94

Implemented Page components now and added ToDos for future URL updates.

2023-12-05 00:25 UTC, jyalenkatian requested changes
@wajihqazi94 Review comments have been added.
Overview of notes:
1.  Variable names should be camelCase
2. No need to have ids inside the divs, the accordion takes care of it
3. CodeSample tags should be self-closing since there are no children
4. `<a>` tags that point outside of the site should have `target="_blank" rel="noopener noreferrer"` attributes
5. Content inside of `<code>` tags should be surrounded by curly brackets & ticks { ` `` ` }
6. I noticed there is no Example 3 section and it goes from 2 to 4. Might be good to just renumber the 4 & 5?

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +}></CodeSample>
```suggestion
}/>
```
This component can be self-closing since there are no children.

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +const MultiCallErrors: ReactNode = (
Variable name should be camel case.

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +    <div className="paragraph" id="multiCallErrors">
No need to have the id here.

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +}></CodeSample>
```suggestion
}/>
```
This component can be self-closing since there are no children.

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +}></CodeSample>
```suggestion
}/>
```
This component can be self-closing since there are no children.

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +            Below is an example of the error result. The <code className="small-code-sample">requestIndex</code> property contains the index of the call that failed.
```suggestion
            Below is an example of the error result. The <code className="small-code-sample">{`requestIndex`}</code> property contains the index of the call that failed.
```

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +const APIClientSupport: ReactNode = (
Variable name should be camel case.

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +}></CodeSample>
```suggestion
}/>
```
This component can be self-closing since there are no children.

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +const MultiCallFAQ: ReactNode = (
Variable name should be camel case.

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +            The MyGeotab API supports brotli, gzip and deflate compression. To use either of these compression methods, include the HTTP header for “Accept-Encoding”. For example:
brotli, gzip, & deflate should be italicized.

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +        "summary": "PropertSelector BETA",
```suggestion
        "summary": "PropertySelector BETA",
```

2023-12-05 00:25 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
> +    <div className="table-content">
```suggestion
    <div className="table-container">
```

2023-12-06 02:02 UTC, jyalenkatian requested changes
@wajihqazi94 Majority of remaining changes are updating the language field for CodeSample components.

2023-12-06 08:57 UTC, wajihqazi94 commented on src/pages/myGeotab/guides/concepts.tsx
>              Accept-Encoding: brotli, gzip, deflate
Do you mean the "Accept-Encoding: brotli, gzip, deflate" line?

2023-12-06 22:45 UTC, jyalenkatian commented on src/pages/myGeotab/guides/concepts.tsx
>              Accept-Encoding: brotli, gzip, deflate
@wajihqazi94 Yes

2023-12-13 19:08 UTC, jyalenkatian approved these changes

2023-12-13 19:09 UTC, merged