Intgr 215
Geotab/sdk pull request #378
Opened 2023-12-06 03:44 UTC by kmets89

2023-12-06 03:58 UTC, kmets89 commented on src/pages/myGeotab/apiReference/object.tsx
> +        <table className="table-container">
this isn't in a table in the figma, did something change?

2023-12-06 03:58 UTC, kmets89 commented on src/pages/myGeotab/apiReference/method.tsx
> +        "breadCrumbItems": ["MYG", "API Reference", "Methods", methodId]
figma shows (...) after each method name, in breadcrumb and title

2023-12-06 03:58 UTC, kmets89 commented on src/pages/myGeotab/apiReference/methods.tsx
> +            <Header title={methodDetails[0]}>
missing (...) after title

2023-12-06 03:58 UTC, kmets89 commented on src/pages/myGeotab/apiReference/myGParser.ts
async needs to be removed from method names eg: AuthenticateAsync should be Authenticate
entries should be ordered alphabetically
API object is missing from objects page

2023-12-20 00:48 UTC, jyalenkatian commented on package-lock.json
This file needs to be in the gitignore

2023-12-20 00:48 UTC, jyalenkatian commented on .npmrc
This files needs to be in the gitignore

2023-12-20 00:48 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/method.tsx
> +        "breadCrumbItems": ["MYG", "API Reference", "Methods", methodId + "(...)"]
There should be a space before the (...)

2023-12-20 00:48 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/method.tsx
> +    const ParamTable: ReactNode = <div className="paragraph">
This variable should be camelCase & the content should be inside parentheses.

2023-12-20 00:48 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/method.tsx
> +    const ReturnDescription: ReactNode = <div className="paragraph">
This variable should be camelCase & the content should be inside parentheses.

2023-12-20 00:48 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/method.tsx
> +    const TryMeCodeBlock: ReactNode = <div className="paragraph">
This variable should be camelCase & the content should be inside parentheses.

2023-12-20 00:48 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methods.tsx
> +                {methodDetails[0] + "(...)"}
There should be a space before (...)

2023-12-20 00:48 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/object.tsx
> +    )
Missing semicolon

2023-12-20 00:48 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/object.tsx
> +            "summary": "introduction"
```suggestion
            "summary": "Introduction"
```

2024-01-09 08:33 UTC, jyalenkatian requested changes
@wajihqazi94 Comments have been left in the PR.

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methods.tsx
> +    "breadCrumbItems": ["MYG", "API REFERENCE", "METHODS"]
Revert casing. Should be how it was before.

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methods.tsx
Line 50 should have JSX.Element return type for component

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/object.tsx
> +    const properties = storedObjectData.properties;
Add data types for variables.

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/object.tsx
> +export default function Object() {
```suggestion
export default function Object():JSX.Element {
```

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/object.tsx
> +        "breadCrumbItems": ["MYG", "API REFERENCE", "OBJECTS", objectId.toUpperCase()]
Shouldn't be all uppercase, title casing instead.

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/object.tsx
> +        </Page>
Can be self closing
```suggestion
        <Page section={HeaderSections.MyGeotab} pageTitle={pageTitle} tableOfContents={pageSections} />
```

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/objects.tsx
> +    "breadCrumbItems": ["MYG", "API RERFENCE", "OBJECTS"]
Revert

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/objects.tsx
>  export default function Objects() {
```suggestion
export default function Objects(): JSX.Element {
```

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/objects.tsx
>      let pageSectionObject = {
```suggestion
    let pageSectionObject: TableOfContentsItem = {
```

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/objects.tsx
>  const objectItems = objects.map((objectDetails: any) => {
`any` should be replaced with the actual type here. objects & objectItems should also have a type specified.

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/renderStringWithUrl.tsx
>  export default function RenderStringWithLinks(text: string) {
Specify what data type is being returned from this function and the same for the rest of the variables/loops/functions in this file.

2024-01-09 08:33 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/myGParser.ts
Types for variables throughout the file need to be specified.

2024-01-09 17:55 UTC, jyalenkatian approved these changes

2024-01-09 17:55 UTC, merged