INTGR-251: feat / Implement hardware "Python Code Samples" page
Geotab/sdk pull request #384
Opened 2023-12-11 21:14 UTC by PCGeotab

INTGR-251: feat / Implement hardware "Python Code Samples" page and refactor spelling for "usingCustomTelematicsDevices" page

2023-12-12 22:50 UTC, kmets89 requested changes

2023-12-12 22:50 UTC, kmets89 commented on src/pages/hardware/samples/python.tsx
> +def checksum(message):
please use tab (or 4 spaces) indenting, not one space. I know that's what they have on the current site but it's silly

2023-12-12 23:59 UTC, PCGeotab commented
Code indents have been increased to 4 spaces.

2023-12-13 01:40 UTC, kmets89 approved these changes

2023-12-13 01:40 UTC, merged