INTGR-254
Geotab/sdk pull request #399
Opened 2023-12-14 06:35 UTC by wajihqazi94

2023-12-14 23:49 UTC, PCGeotab commented
- All instances of `&nbsp;` should be replaced with JSX syntax, e.g. `{"}`
- Table styling should be different, you could utilize our existing table styling like so:
![Screenshot 2023-12-14 154845](https://github.com/Geotab/sdk/assets/91985640/f2db3011-5700-4454-9d83-a2d5bc15f476)
![Screenshot 2023-12-14 154829](https://github.com/Geotab/sdk/assets/91985640/f901e3b0-3143-4c98-9ffd-cafb4c23d21f)
![Screenshot 2023-12-14 154737](https://github.com/Geotab/sdk/assets/91985640/d19b436d-1af4-4fde-853f-7a64d90cf8d6)

2023-12-20 00:14 UTC, jyalenkatian requested changes
@wajihqazi94 Two things left to fix.

2023-12-20 00:14 UTC, jyalenkatian commented on src/pages/hardware/developingAnIOX/MIMEProtocol.tsx
> +        <table>
This table needs to be in a `<div className="table-container">`

2023-12-20 00:14 UTC, jyalenkatian commented on src/pages/hardware/developingAnIOX/MIMEProtocol.tsx
> +    "breadCrumbItems": ["Hardware", "Developing an IOX", "MIME Protocol"]
```suggestion
    "breadCrumbItems": ["Hardware", "Guides", "MIME Protocol"]
```
There won't be a "Developing an IOX" section in the new site, so let's replace it with "Guides". Can you also update the folder name to 'guides'?

2023-12-20 17:41 UTC, merged