Intgr 256
Geotab/sdk pull request #418
Opened 2024-01-08 22:58 UTC by kmets89

2024-01-11 02:35 UTC, jyalenkatian requested changes
@kmets89 Comments have been added to the PR.

2024-01-11 02:35 UTC, jyalenkatian commented on src/components/SearchModal/SearchResultTabContent.tsx
> +      return results;
Can simplify a bit
```suggestion
    case SearchSections.APIReference:
      return results.filter(result => result.category === "reference");
    case SearchSections.Guides:
      return results.filter(result => result.category === "guide");
    case SearchSections.All:
    default:
      return results;
```

2024-01-11 02:35 UTC, jyalenkatian commented on src/components/SearchModal/ResultsList.tsx
> +export default function ResultsList(props: { results: SearchResult[] }): JSX.Element {
Should the props be made into an interface?

2024-01-11 02:35 UTC, jyalenkatian commented on src/components/SearchModal/utils/searchUtils.tsx
> +export const findHeaderId = (searchId: number, matchTerms: MatchInfo,): string | null => {
Trailing comma
```suggestion
export const findHeaderId = (searchId: number, matchTerms: MatchInfo): string | null => {
```

2024-01-11 21:37 UTC, kmets89 commented on src/components/SearchModal/SearchModal.tsx
> +miniSearch.addAll(searchIndex); //TODO: should we do this asynchronously? how do we handle the UI until it's ready
let's revisit this once all search stuff is done

2024-01-12 22:58 UTC, jyalenkatian requested changes

2024-01-12 22:58 UTC, jyalenkatian commented on src/components/apiReference/Method.tsx
> +    const parameterParagaphs: ReactNode = (
Typo that we missed in the previous branch

```suggestion
    const parameterParagraphs: ReactNode = (
```

2024-01-12 22:58 UTC, jyalenkatian commented on src/components/apiReference/Method.tsx
> +            details: parameterParagaphs
Typo that we missed in the previous branch

```suggestion
            details: parameterParagraphs
```

2024-01-12 22:58 UTC, jyalenkatian commented on src/components/apiReference/Object.tsx
>      const propertyParagaphs: ReactNode = (
Typo that we missed in the previous branch
```suggestion
    const propertyParagraphs: ReactNode = (
```

2024-01-12 22:58 UTC, jyalenkatian commented on src/components/apiReference/Object.tsx
> +            details: propertyParagaphs
Typo that we missed in the previous branch

```suggestion
            details: propertyParagraphs
```

2024-01-12 23:09 UTC, jyalenkatian approved these changes

2024-01-12 23:09 UTC, merged