INTGR-290: As a Geotab SDK site user, I would like to see examples in Javascript, C#, & Python for MyGeotab SDK methods [Part 3]
Geotab/sdk pull request #421
Opened 2024-01-12 00:20 UTC by PCGeotab

https://jira.geotab.com/browse/INTGR-290

Methods to write examples for:

GetTimeZones
Javascript already exists? Yes
GetVersion
Javascript already exists? Yes
GetVersionInformation
Javascript already exists? Yes
OptimizeWaypoints
Javascript already exists? Yes
Remove
Javascript already exists? Yes
Set
Javascript already exists? Yes
UploadMediaFile
Javascript already exists? No
DownloadMediaFile
Javascript already exists? No

2024-01-13 01:02 UTC, kmets89 commented
let's hold off on this until Joseph's branch is done so all changes are visible

2024-01-17 02:51 UTC, jyalenkatian requested changes

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    csharp: `await api.CallAsync<object>("GetVersionInformation");`,
```suggestion
    csharp: `await api.CallAsync<VersionInformation>("GetVersionInformation");`,
```

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    var waypointsList = new List<Waypoint>
Tabbing needs to be fixed, missing two waypoints, and missing descriptions for each waypoint.

```suggestion
    IList<Waypoint> waypointsList = new List<Waypoint>
```

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    python: `api.call("OptimizeWaypoints", waypoints=[
Fix tabbing

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    Console.WriteLine("Enter the name of the zone that you want to remove:");
Fix tabbing

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +
Fix tabbing

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    Console.WriteLine("Enter current zone name: ");
Fix tabbing

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    var zones = await api.CallAsync<List<Zone>>("Get", typeof(Zone), new { search = new { name = $"%{currentZoneName}%"}});
```suggestion
    IList<Zone> zones = await api.CallAsync<List<Zone>>("Get", typeof(Zone), new { search = new { name = $"%{currentZoneName}%"}});
```

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +        new_zone_name = input("Enter new zone name: ")
Fix tabbing

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +  },
Fix tabbing

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    string inputfile = ""<your media file here>"; // the path to the file to upload
```suggestion
    string inputfile = "<your media file here>"; // the path to the file to upload
```

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    var mediaFile = new MediaFile
```suggestion
    MediaFile mediaFile = new MediaFile
```

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    var solutionId = Id.Create(Guid.NewGuid()); // the unique solution ID of the integration
```suggestion
    Id solutionId = Id.Create(Guid.NewGuid()); // the unique solution ID of the integration
```

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    var file = new FileInfo(inputfile);
```suggestion
    FileInfo file = new FileInfo(inputfile);
```

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    var mediaFile = (await api.CallAsync<IEnumerable<MediaFile>>("Get", typeof(MediaFile), new { search = new MediaFileSearch(mediafileId) })).FirstOrDefault();
```suggestion
    MediaFile mediaFile = (await api.CallAsync<IEnumerable<MediaFile>>("Get", typeof(MediaFile), new { search = new MediaFileSearch(mediafileId) })).FirstOrDefault();
```

2024-01-17 02:51 UTC, jyalenkatian commented on src/pages/myGeotab/apiReference/methodsCodeSamples.ts
> +    var mediafileId = Id.Create(Console.ReadLine());
```suggestion
    Id mediafileId = Id.Create(Console.ReadLine());
```

2024-01-18 02:13 UTC, jyalenkatian requested changes

2024-01-18 23:01 UTC, jyalenkatian approved these changes

2024-01-18 23:01 UTC, merged